site_url: http://localhost:1313

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey


backend:
#  name: test-repo
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

##------
# Alternate method, this requires decap-server package:
# `npm install decap-server`, then running `npx decap-server`
# that starts a local proxy server at localhost:8081

#backend:
#  name: git-gateway
#  branch: master

local_backend: true
#------

collections:
  - name: home
    label: Homepage
    files:
      - label: Home page
        name: _index
        file: content/_index.md
        frontmatter_format: yaml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Draft, name: draft, widget: boolean, required: false }
          - { label: Date, name: date, widget: datetime }
          - { label: Body, name: body, widget: markdown, default: rich_text, required: false }
          - label: card
            name: card
            widget: object
            fields:
              - label: Honorific
                name: honorific
                widget: select
                options: [ "Mr.", "Ms." ]
                #  - { label: "Mr.", value: "Mr." }
                #  - { label: "Ms.", value: "Ms." }
              - label: Name
                name: name
                widget: string
              - label: Portrait
                name: portrait
                widget: string
              - label: Position
                name: position
                widget: string
  - name: cats
    label: Cats
    folder: content/cats
    create: true
    extension: md
    fields:
       - { label: Title, name: title, widget: string }
       - { label: Draft, name: draft, widget: boolean, required: false }
